apiVersion: v1
kind: Pod
metadata:
  name: candy-service
spec:
  containers:
  - name: candy-service
    image: linuxacademycontent/candy-service:2
    livenessProbe:
      httpGet: 
        path: /healthz 
        port: 8081
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet: 
        path: / 
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5      