version: "2"

# http 1.1 nginx docker 
  nginx:
    image: nginx:stable
    restart: always
    ports:
    - "8000:80"
    #- "8888:8888"
    volumes:
            #- "/etc/letsencrypt:/etc/letsencrypt"      
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./html:/usr/abc/html:ro"
