version: "2"
# http 2 nginx docker
services:
  nginx:
    image: nginx:stable
    restart: always
    ports:
    - "80:80"       
    - "443:443"
    #- "8888:8888"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt/"      
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./html:/usr/abc/html:ro"
