version: "2"

services:
  nginx:
    # network_mode: "host"      
    image: nginx:stable
    restart: always
    ports:
    - "8000:8080"
    #- "8888:8888"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      # - "./html:/usr/abc/html:ro"
      # - "./images:/usr/abc/images:ro"

  app1:
    ports:
        - '5555:9999'
    environment:
        - appid=5555
    image: nodeapp
  app2:
    ports:
        - '6666:9999'
    environment:
        - appid=6666
    image: nodeapp
  app3:
    ports:
        - '7777:9999'
    environment:
        - appid=7777
    image: nodeapp
  app4:
    ports:
        - '8888:9999'
    environment:
        - appid=8888
    image: nodeapp

