apiVersion: v1
kind: Pod
metadata: 
  name: candy-service-pod
spec:
  serviceAccountName: candy-svc
  securityContext:
    fsGroup: 2000
  containers:
  - name: candy-service-container
    image: linuxacademycontent/candy-service:1
    volumeMounts:
    - name: candy-service-config-volume
      mountPath: /etc/candy-service
    env:
    - name: DB_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: db-password-secret
          key: db-password      
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"        
  volumes:
  - name: candy-service-config-volume
    configMap:
      name: candy-service-config 