apiVersion: v1
kind: Pod
metadata: 
  name: my-configmap-pod
  namespace: my-ns
  labels: 
    app: myapp1
spec:
  containers:
  - name: myapp1-container
    image: busybox
    command: ['sh', '-c', 'echo $(MY_VAR) && sleep 3600']
    env:
    - name: MY_VAR
      valueFrom:
        configMapKeyRef:
          name: my-config-map
          key: myKy