apiVersion: v1
kind: Pod
metadata: 
  name: my-configmap-volume-pod
  namespace: my-ns
  labels: 
    app: myapp1
spec:
  containers:
  - name: myapp1-container
    image: busybox
    command: ['sh', '-c', 'echo $(cat /etc/config/anotherKey) && sleep 3600']
    volumeMounts: 
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: my-config-map