apiVersion: v1
kind: Pod
metadata: 
  name: my-command-pod
  namespace: my-ns
  labels: 
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['echo']
  restartPolicy: Never