apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app: nginx
# specification of the deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
# specification of the container          
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80