apiVersion: v1
kind: Pod
metadata: 
  name: my-pod1
  namespace: my-ns
  labels: 
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello World && sleep 3600']