apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  namespace: web
  labels: 
    app: nginx-server1
spec:
  containers:
  - name: nginx-container
    image: nginx
    command: ['nginx']
    args: ['-g', 'daemon off;', '-q']
    ports:
    - containerPort: 80

