apiVersion: v1
kind: Pod
metadata: 
  name: my-securitycontext-pod
  namespace: my-ns
  labels: 
    app: myapp1
spec:
  securityContext:
    runAsUser: 2001
    fsGroup: 3001
  containers:
  - name: myapp1-container
    image: busybox
    command: ['sh', '-c', 'cat /message/message.txt && sleep 3600']
    volumeMounts: 
    - name: message-volume
      mountPath: /message
  volumes:
  - name: message-volume
    hostPath:
      path: /etc/message