apiVersion: v1
kind: Pod
metadata: 
  name: busybox
  labels: 
    app: busybox-testing-app
spec:
  containers:
  - name: busybox-testing-container
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'while true; do sleep 3600; done']