apiVersion: v1
kind: Pod
metadata:
  name: my-pvc-pod
spec:
  containers: 
  - image: busybox
    name: busybox 
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done;"]
    volumeMounts:
    - name: my-storage
      mountPath: "/mnt/storage"
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: my-pvc
