apiVersion: v1
kind: Pod
metadata: 
  name: my-readiness-pod
spec:
  containers:
  - name: myreadiness-container
    image: nginx
    livenessProbe:
      httpGet: 
        path: / 
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5